services:
  stock-fetcher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    networks:
      - intrinsic_backend-network
    volumes:
      - stock-fetcher-logs:/var/log/stock-fetcher

networks:
  intrinsic_backend-network:
    external: true

volumes:
  stock-fetcher-logs: